[book]
authors = ["Xie Yu"]
language = "en"
multilingual = false
src = "src"
title = "blog"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

#[preprocessor.graphviz]
#command = "mdbook-graphviz"
